### PR TITLE
Add check for symlinks in library

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by bblanchon** [comment]
I think this feature might be broken: I just tested version 1.1.4 with a repository that contains a symlink, but it didn't detect it.

**Comment by silvanocerza** [comment]
Hi @bblanchon can you tell us which repo so we can test it?

**Comment by bblanchon** [comment]
It was [ArduinoJson](https://github.com/bblanchon/ArduinoJson), but I removed the symlink a few hours ago, so you'll have to check out the tag `v6.18.1`.
I doubt that this issue is specific to ArduinoJson's repo; you can probably reproduce the issue with any library.
I looked at the test cases and there doesn't seem to be one covering this feature.

**Comment by per1234** [comment]
>what do you think?

We prohibit any type of symlink in libraries, so this must be fixed:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager

Thanks for the report @bblanchon!

**Comment by bblanchon** [comment]
You're welcome, @per1234.
ArduinoJson 6.18.1 is missing from the Library Manager; I'm assuming it's due to the symlink.

**Comment by per1234** [comment]
>ArduinoJson 6.18.1 is missing from the Library Manager; I'm assuming it's due to the symlink.

That is correct. We now provide a dedicated web page with the indexer logs for each of the Library Manager libraries. You can see the logs for ArduinoJson here:
https://downloads.arduino.cc/libraries/logs/github.com/bblanchon/ArduinoJson/
Even though Arduino Lint dropped the ball on this one, there is an additional symlink check built in to [`arduino/libraries-repository-engine`](https://github.com/arduino/libraries-repository-engine) that caught the symlink before the library could be added to the index:
```
2021/07/15 16:47:17 Error syncing library: Error while zipping library: Symlink not allowed: /home/arduino/workspace/workspace/Librariesv2/gitclones/github.com/bblanchon/ArduinoJson/extras/ci/espidf/components/ArduinoJson -> ../../../..
```

**Comment by bblanchon** [comment]
Thanks, @per1234. I didn't know the log files were publicly accessible; this is awesome!

**Pull request merged**
